export type FestivalTemplate = {
  slug: string;
  name: string;
  region: string;
  greeting: string;
  subline: string;
  motif: string;
  bg: string;
  accent: string;
  fg: string;
  image: string;
  layout: number;
};

export const FESTIVALS: FestivalTemplate[] = [
  {
    "slug": "diwali",
    "name": "Diwali",
    "region": "Pan-India",
    "greeting": "Shubh Deepavali",
    "subline": "May your home glow with joy, prosperity and new beginnings.",
    "motif": "light",
    "bg": "#2a124f",
    "accent": "#ffb703",
    "fg": "#ffffff",
    "image": "/festivals/diwali.svg",
    "layout": 0
  },
  {
    "slug": "holi",
    "name": "Holi",
    "region": "Pan-India",
    "greeting": "Happy Holi",
    "subline": "Celebrate colour, laughter and togetherness.",
    "motif": "color",
    "bg": "#fff4e6",
    "accent": "#ef476f",
    "fg": "#0f172a",
    "image": "/festivals/holi.svg",
    "layout": 1
  },
  {
    "slug": "dussehra",
    "name": "Dussehra / Vijayadashami",
    "region": "Pan-India",
    "greeting": "Happy Dussehra",
    "subline": "May courage and goodness always rise above every challenge.",
    "motif": "fire",
    "bg": "#fff7ed",
    "accent": "#ea580c",
    "fg": "#0f172a",
    "image": "/festivals/dussehra.svg",
    "layout": 2
  },
  {
    "slug": "navratri",
    "name": "Navratri",
    "region": "Pan-India",
    "greeting": "Shubh Navratri",
    "subline": "Nine nights of devotion, dance and divine energy.",
    "motif": "dance",
    "bg": "#3b0764",
    "accent": "#f59e0b",
    "fg": "#ffffff",
    "image": "/festivals/navratri.svg",
    "layout": 3
  },
  {
    "slug": "durga-puja",
    "name": "Durga Puja",
    "region": "East India",
    "greeting": "Shubho Durga Puja",
    "subline": "Celebrate strength, grace and the joy of coming together.",
    "motif": "lotus",
    "bg": "#7f1d1d",
    "accent": "#facc15",
    "fg": "#ffffff",
    "image": "/festivals/durga-puja.svg",
    "layout": 0
  },
  {
    "slug": "ganesh-chaturthi",
    "name": "Ganesh Chaturthi",
    "region": "Pan-India",
    "greeting": "Ganpati Bappa Morya",
    "subline": "May wisdom, prosperity and happiness enter every home.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/ganesh-chaturthi.svg",
    "layout": 1
  },
  {
    "slug": "janmashtami",
    "name": "Janmashtami",
    "region": "Pan-India",
    "greeting": "Happy Janmashtami",
    "subline": "Celebrate devotion, joy and the timeless melody of Krishna.",
    "motif": "peacock",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/janmashtami.svg",
    "layout": 2
  },
  {
    "slug": "raksha-bandhan",
    "name": "Raksha Bandhan",
    "region": "Pan-India",
    "greeting": "Happy Raksha Bandhan",
    "subline": "A celebration of love, trust and a bond that stays close.",
    "motif": "thread",
    "bg": "#fff1f2",
    "accent": "#e11d48",
    "fg": "#0f172a",
    "image": "/festivals/raksha-bandhan.svg",
    "layout": 3
  },
  {
    "slug": "makar-sankranti",
    "name": "Makar Sankranti",
    "region": "Pan-India",
    "greeting": "Happy Makar Sankranti",
    "subline": "Let your dreams rise high with the season of harvest and hope.",
    "motif": "kite",
    "bg": "#e0f2fe",
    "accent": "#0284c7",
    "fg": "#0f172a",
    "image": "/festivals/makar-sankranti.svg",
    "layout": 0
  },
  {
    "slug": "pongal",
    "name": "Pongal",
    "region": "Tamil Nadu",
    "greeting": "Happy Pongal",
    "subline": "May the harvest season bring abundance, gratitude and warmth.",
    "motif": "harvest",
    "bg": "#fef3c7",
    "accent": "#b45309",
    "fg": "#0f172a",
    "image": "/festivals/pongal.svg",
    "layout": 1
  },
  {
    "slug": "lohri",
    "name": "Lohri",
    "region": "Punjab & North India",
    "greeting": "Happy Lohri",
    "subline": "Celebrate the warmth of the fire, music and togetherness.",
    "motif": "fire",
    "bg": "#451a03",
    "accent": "#fb923c",
    "fg": "#ffffff",
    "image": "/festivals/lohri.svg",
    "layout": 2
  },
  {
    "slug": "vaisakhi",
    "name": "Baisakhi / Vaisakhi",
    "region": "Punjab & North India",
    "greeting": "Happy Baisakhi",
    "subline": "A joyful harvest, a fresh season and new beginnings.",
    "motif": "harvest",
    "bg": "#fff7ed",
    "accent": "#f59e0b",
    "fg": "#0f172a",
    "image": "/festivals/vaisakhi.svg",
    "layout": 3
  },
  {
    "slug": "onam",
    "name": "Onam",
    "region": "Kerala",
    "greeting": "Happy Onam",
    "subline": "Celebrate prosperity, tradition and the beauty of togetherness.",
    "motif": "flower",
    "bg": "#ecfdf5",
    "accent": "#059669",
    "fg": "#0f172a",
    "image": "/festivals/onam.svg",
    "layout": 0
  },
  {
    "slug": "vishu",
    "name": "Vishu",
    "region": "Kerala",
    "greeting": "Happy Vishu",
    "subline": "May the new year begin with abundance, light and hope.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/vishu.svg",
    "layout": 1
  },
  {
    "slug": "ugadi",
    "name": "Ugadi",
    "region": "Karnataka, Andhra Pradesh & Telangana",
    "greeting": "Happy Ugadi",
    "subline": "Wishing you a fresh year filled with purpose and possibilities.",
    "motif": "leaf",
    "bg": "#f0fdf4",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/ugadi.svg",
    "layout": 2
  },
  {
    "slug": "gudi-padwa",
    "name": "Gudi Padwa",
    "region": "Maharashtra & Goa",
    "greeting": "Happy Gudi Padwa",
    "subline": "Welcome the new year with joy, success and positivity.",
    "motif": "flag",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/gudi-padwa.svg",
    "layout": 3
  },
  {
    "slug": "akshaya-tritiya",
    "name": "Akshaya Tritiya",
    "region": "Pan-India",
    "greeting": "Shubh Akshaya Tritiya",
    "subline": "May every good beginning grow into lasting prosperity.",
    "motif": "lotus",
    "bg": "#fffbeb",
    "accent": "#d97706",
    "fg": "#0f172a",
    "image": "/festivals/akshaya-tritiya.svg",
    "layout": 0
  },
  {
    "slug": "maha-shivratri",
    "name": "Maha Shivratri",
    "region": "Pan-India",
    "greeting": "Har Har Mahadev",
    "subline": "A night of devotion, stillness and inner strength.",
    "motif": "moon",
    "bg": "#0f172a",
    "accent": "#60a5fa",
    "fg": "#ffffff",
    "image": "/festivals/maha-shivratri.svg",
    "layout": 1
  },
  {
    "slug": "ram-navami",
    "name": "Ram Navami",
    "region": "Pan-India",
    "greeting": "Happy Ram Navami",
    "subline": "May truth, courage and compassion guide every step.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#ea580c",
    "fg": "#0f172a",
    "image": "/festivals/ram-navami.svg",
    "layout": 2
  },
  {
    "slug": "hanuman-jayanti",
    "name": "Hanuman Jayanti",
    "region": "Pan-India",
    "greeting": "Happy Hanuman Jayanti",
    "subline": "May strength, devotion and courage stay with you always.",
    "motif": "fire",
    "bg": "#ffedd5",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/hanuman-jayanti.svg",
    "layout": 3
  },
  {
    "slug": "basant-panchami",
    "name": "Basant Panchami",
    "region": "North & East India",
    "greeting": "Happy Basant Panchami",
    "subline": "Welcome spring with learning, creativity and bright beginnings.",
    "motif": "flower",
    "bg": "#fef9c3",
    "accent": "#eab308",
    "fg": "#0f172a",
    "image": "/festivals/basant-panchami.svg",
    "layout": 0
  },
  {
    "slug": "govardhan-puja",
    "name": "Govardhan Puja",
    "region": "North India",
    "greeting": "Shubh Govardhan Puja",
    "subline": "Celebrate gratitude, protection and the blessings of nature.",
    "motif": "mountain",
    "bg": "#ecfccb",
    "accent": "#65a30d",
    "fg": "#0f172a",
    "image": "/festivals/govardhan-puja.svg",
    "layout": 1
  },
  {
    "slug": "bhai-dooj",
    "name": "Bhai Dooj",
    "region": "Pan-India",
    "greeting": "Happy Bhai Dooj",
    "subline": "Celebrate the warmth and strength of sibling love.",
    "motif": "thread",
    "bg": "#fdf2f8",
    "accent": "#db2777",
    "fg": "#0f172a",
    "image": "/festivals/bhai-dooj.svg",
    "layout": 2
  },
  {
    "slug": "dhanteras",
    "name": "Dhanteras",
    "region": "Pan-India",
    "greeting": "Shubh Dhanteras",
    "subline": "May this auspicious day bring health, abundance and prosperity.",
    "motif": "light",
    "bg": "#422006",
    "accent": "#fbbf24",
    "fg": "#ffffff",
    "image": "/festivals/dhanteras.svg",
    "layout": 3
  },
  {
    "slug": "karwa-chauth",
    "name": "Karwa Chauth",
    "region": "North & West India",
    "greeting": "Happy Karwa Chauth",
    "subline": "A celebration of love, commitment and cherished traditions.",
    "motif": "moon",
    "bg": "#4c0519",
    "accent": "#fb7185",
    "fg": "#ffffff",
    "image": "/festivals/karwa-chauth.svg",
    "layout": 0
  },
  {
    "slug": "chhath-puja",
    "name": "Chhath Puja",
    "region": "Bihar, Jharkhand & Uttar Pradesh",
    "greeting": "Chhath Puja",
    "subline": "Offer gratitude to the sun and celebrate faith, purity and devotion.",
    "motif": "sun",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/chhath-puja.svg",
    "layout": 1
  },
  {
    "slug": "teej",
    "name": "Teej",
    "region": "North & West India",
    "greeting": "Happy Teej",
    "subline": "Celebrate monsoon, tradition, love and festive colour.",
    "motif": "leaf",
    "bg": "#ecfdf5",
    "accent": "#10b981",
    "fg": "#0f172a",
    "image": "/festivals/teej.svg",
    "layout": 2
  },
  {
    "slug": "hartalika-teej",
    "name": "Hartalika Teej",
    "region": "North & Central India",
    "greeting": "Hartalika Teej",
    "subline": "Wishing you devotion, strength and happiness.",
    "motif": "leaf",
    "bg": "#fdf2f8",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/hartalika-teej.svg",
    "layout": 3
  },
  {
    "slug": "gangaur",
    "name": "Gangaur",
    "region": "Rajasthan",
    "greeting": "Happy Gangaur",
    "subline": "Celebrate spring, devotion and Rajasthan’s vibrant traditions.",
    "motif": "flower",
    "bg": "#fff1f2",
    "accent": "#e11d48",
    "fg": "#0f172a",
    "image": "/festivals/gangaur.svg",
    "layout": 0
  },
  {
    "slug": "nag-panchami",
    "name": "Nag Panchami",
    "region": "Pan-India",
    "greeting": "Happy Nag Panchami",
    "subline": "May this sacred day bring protection, peace and blessings.",
    "motif": "leaf",
    "bg": "#f0fdf4",
    "accent": "#15803d",
    "fg": "#0f172a",
    "image": "/festivals/nag-panchami.svg",
    "layout": 1
  },
  {
    "slug": "guru-purnima",
    "name": "Guru Purnima",
    "region": "Pan-India",
    "greeting": "Happy Guru Purnima",
    "subline": "Gratitude to the teachers who guide, inspire and illuminate.",
    "motif": "light",
    "bg": "#f5f3ff",
    "accent": "#7c3aed",
    "fg": "#0f172a",
    "image": "/festivals/guru-purnima.svg",
    "layout": 2
  },
  {
    "slug": "buddha-purnima",
    "name": "Buddha Purnima",
    "region": "Pan-India",
    "greeting": "Buddha Purnima",
    "subline": "May peace, compassion and mindfulness light your path.",
    "motif": "lotus",
    "bg": "#fffbeb",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/buddha-purnima.svg",
    "layout": 3
  },
  {
    "slug": "mahavir-jayanti",
    "name": "Mahavir Jayanti",
    "region": "Jain",
    "greeting": "Mahavir Jayanti",
    "subline": "Celebrate non-violence, truth and compassion.",
    "motif": "lotus",
    "bg": "#f0fdf4",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/mahavir-jayanti.svg",
    "layout": 0
  },
  {
    "slug": "paryushan",
    "name": "Paryushan",
    "region": "Jain",
    "greeting": "Micchami Dukkadam",
    "subline": "A time for reflection, forgiveness and inner peace.",
    "motif": "lotus",
    "bg": "#faf5ff",
    "accent": "#9333ea",
    "fg": "#0f172a",
    "image": "/festivals/paryushan.svg",
    "layout": 1
  },
  {
    "slug": "guru-nanak-gurpurab",
    "name": "Guru Nanak Gurpurab",
    "region": "Sikh",
    "greeting": "Happy Gurpurab",
    "subline": "May wisdom, seva and compassion guide every day.",
    "motif": "light",
    "bg": "#eff6ff",
    "accent": "#1d4ed8",
    "fg": "#0f172a",
    "image": "/festivals/guru-nanak-gurpurab.svg",
    "layout": 2
  },
  {
    "slug": "guru-gobind-singh-jayanti",
    "name": "Guru Gobind Singh Jayanti",
    "region": "Sikh",
    "greeting": "Happy Gurpurab",
    "subline": "Honouring courage, equality and a life of service.",
    "motif": "flag",
    "bg": "#fff7ed",
    "accent": "#f59e0b",
    "fg": "#0f172a",
    "image": "/festivals/guru-gobind-singh-jayanti.svg",
    "layout": 3
  },
  {
    "slug": "hola-mohalla",
    "name": "Hola Mohalla",
    "region": "Punjab",
    "greeting": "Hola Mohalla",
    "subline": "Celebrate courage, community and the spirit of seva.",
    "motif": "flag",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/hola-mohalla.svg",
    "layout": 0
  },
  {
    "slug": "eid-ul-fitr",
    "name": "Eid al-Fitr",
    "region": "Muslim",
    "greeting": "Eid Mubarak",
    "subline": "May your celebration be filled with peace, gratitude and joy.",
    "motif": "moon",
    "bg": "#052e16",
    "accent": "#34d399",
    "fg": "#ffffff",
    "image": "/festivals/eid-ul-fitr.svg",
    "layout": 1
  },
  {
    "slug": "eid-ul-adha",
    "name": "Eid al-Adha",
    "region": "Muslim",
    "greeting": "Eid Mubarak",
    "subline": "Wishing you faith, generosity and togetherness.",
    "motif": "moon",
    "bg": "#064e3b",
    "accent": "#fbbf24",
    "fg": "#ffffff",
    "image": "/festivals/eid-ul-adha.svg",
    "layout": 2
  },
  {
    "slug": "muharram",
    "name": "Muharram",
    "region": "Muslim",
    "greeting": "Muharram",
    "subline": "A time of remembrance, reflection and compassion.",
    "motif": "moon",
    "bg": "#111827",
    "accent": "#9ca3af",
    "fg": "#ffffff",
    "image": "/festivals/muharram.svg",
    "layout": 3
  },
  {
    "slug": "milad-un-nabi",
    "name": "Milad-un-Nabi",
    "region": "Muslim",
    "greeting": "Milad-un-Nabi",
    "subline": "May peace, kindness and blessings be with everyone.",
    "motif": "moon",
    "bg": "#ecfdf5",
    "accent": "#059669",
    "fg": "#0f172a",
    "image": "/festivals/milad-un-nabi.svg",
    "layout": 0
  },
  {
    "slug": "shab-e-barat",
    "name": "Shab-e-Barat",
    "region": "Muslim",
    "greeting": "Shab-e-Barat",
    "subline": "Wishing you forgiveness, peace and heartfelt prayers.",
    "motif": "moon",
    "bg": "#eef2ff",
    "accent": "#6366f1",
    "fg": "#0f172a",
    "image": "/festivals/shab-e-barat.svg",
    "layout": 1
  },
  {
    "slug": "christmas",
    "name": "Christmas",
    "region": "Christian",
    "greeting": "Merry Christmas",
    "subline": "Celebrate joy, kindness and the warmth of being together.",
    "motif": "star",
    "bg": "#064e3b",
    "accent": "#ef4444",
    "fg": "#ffffff",
    "image": "/festivals/christmas.svg",
    "layout": 2
  },
  {
    "slug": "easter",
    "name": "Easter",
    "region": "Christian",
    "greeting": "Happy Easter",
    "subline": "A season of hope, renewal and new beginnings.",
    "motif": "flower",
    "bg": "#fdf2f8",
    "accent": "#8b5cf6",
    "fg": "#0f172a",
    "image": "/festivals/easter.svg",
    "layout": 3
  },
  {
    "slug": "good-friday",
    "name": "Good Friday",
    "region": "Christian",
    "greeting": "Good Friday",
    "subline": "A day of reflection, faith and compassion.",
    "motif": "cross",
    "bg": "#f8fafc",
    "accent": "#475569",
    "fg": "#0f172a",
    "image": "/festivals/good-friday.svg",
    "layout": 0
  },
  {
    "slug": "assamese-bihu",
    "name": "Bihu",
    "region": "Assam",
    "greeting": "Happy Bihu",
    "subline": "Celebrate harvest, music, dance and Assamese culture.",
    "motif": "drum",
    "bg": "#f0fdf4",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/assamese-bihu.svg",
    "layout": 1
  },
  {
    "slug": "hornbill-festival",
    "name": "Hornbill Festival",
    "region": "Nagaland",
    "greeting": "Hornbill Festival",
    "subline": "Celebrate the vibrant cultures, music and traditions of Nagaland.",
    "motif": "feather",
    "bg": "#fff7ed",
    "accent": "#dc2626",
    "fg": "#0f172a",
    "image": "/festivals/hornbill-festival.svg",
    "layout": 2
  },
  {
    "slug": "wangala",
    "name": "Wangala",
    "region": "Meghalaya",
    "greeting": "Happy Wangala",
    "subline": "Celebrate harvest, drums and the traditions of the Garo community.",
    "motif": "drum",
    "bg": "#fef3c7",
    "accent": "#b45309",
    "fg": "#0f172a",
    "image": "/festivals/wangala.svg",
    "layout": 3
  },
  {
    "slug": "chapchar-kut",
    "name": "Chapchar Kut",
    "region": "Mizoram",
    "greeting": "Chapchar Kut",
    "subline": "A joyful celebration of spring, dance and community.",
    "motif": "dance",
    "bg": "#ecfeff",
    "accent": "#0891b2",
    "fg": "#0f172a",
    "image": "/festivals/chapchar-kut.svg",
    "layout": 0
  },
  {
    "slug": "losar",
    "name": "Losar",
    "region": "Ladakh, Sikkim & Himalayan regions",
    "greeting": "Happy Losar",
    "subline": "Welcome the new year with peace, prosperity and fresh beginnings.",
    "motif": "mountain",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/losar.svg",
    "layout": 1
  },
  {
    "slug": "hemis-festival",
    "name": "Hemis Festival",
    "region": "Ladakh",
    "greeting": "Hemis Festival",
    "subline": "Celebrate Himalayan culture, sacred traditions and colourful masks.",
    "motif": "mountain",
    "bg": "#f5f3ff",
    "accent": "#7c3aed",
    "fg": "#0f172a",
    "image": "/festivals/hemis-festival.svg",
    "layout": 2
  },
  {
    "slug": "saga-dawa",
    "name": "Saga Dawa",
    "region": "Himalayan Buddhist regions",
    "greeting": "Saga Dawa",
    "subline": "A sacred season of compassion, merit and mindfulness.",
    "motif": "lotus",
    "bg": "#fffbeb",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/saga-dawa.svg",
    "layout": 3
  },
  {
    "slug": "nuakhai",
    "name": "Nuakhai",
    "region": "Odisha & Chhattisgarh",
    "greeting": "Nuakhai Juhar",
    "subline": "Celebrate the new harvest with gratitude and community.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#65a30d",
    "fg": "#0f172a",
    "image": "/festivals/nuakhai.svg",
    "layout": 0
  },
  {
    "slug": "raja-parba",
    "name": "Raja Parba",
    "region": "Odisha",
    "greeting": "Happy Raja Parba",
    "subline": "Celebrate womanhood, monsoon and the spirit of Odisha.",
    "motif": "flower",
    "bg": "#fdf2f8",
    "accent": "#db2777",
    "fg": "#0f172a",
    "image": "/festivals/raja-parba.svg",
    "layout": 1
  },
  {
    "slug": "bathukamma",
    "name": "Bathukamma",
    "region": "Telangana",
    "greeting": "Happy Bathukamma",
    "subline": "Celebrate flowers, nature and the vibrant spirit of Telangana.",
    "motif": "flower",
    "bg": "#fff1f2",
    "accent": "#e11d48",
    "fg": "#0f172a",
    "image": "/festivals/bathukamma.svg",
    "layout": 2
  },
  {
    "slug": "bonalu",
    "name": "Bonalu",
    "region": "Telangana",
    "greeting": "Happy Bonalu",
    "subline": "Celebrate devotion, tradition and the festive spirit of Telangana.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#ea580c",
    "fg": "#0f172a",
    "image": "/festivals/bonalu.svg",
    "layout": 3
  },
  {
    "slug": "thrissur-pooram",
    "name": "Thrissur Pooram",
    "region": "Kerala",
    "greeting": "Thrissur Pooram",
    "subline": "A grand celebration of rhythm, colour and Kerala tradition.",
    "motif": "drum",
    "bg": "#fffbeb",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/thrissur-pooram.svg",
    "layout": 0
  },
  {
    "slug": "attukal-pongala",
    "name": "Attukal Pongala",
    "region": "Kerala",
    "greeting": "Attukal Pongala",
    "subline": "A celebration of devotion, community and sacred tradition.",
    "motif": "fire",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/attukal-pongala.svg",
    "layout": 1
  },
  {
    "slug": "mysore-dasara",
    "name": "Mysore Dasara",
    "region": "Karnataka",
    "greeting": "Mysore Dasara",
    "subline": "Celebrate heritage, lights and Karnataka’s royal festive spirit.",
    "motif": "palace",
    "bg": "#f5f3ff",
    "accent": "#7c3aed",
    "fg": "#0f172a",
    "image": "/festivals/mysore-dasara.svg",
    "layout": 2
  },
  {
    "slug": "kullu-dussehra",
    "name": "Kullu Dussehra",
    "region": "Himachal Pradesh",
    "greeting": "Kullu Dussehra",
    "subline": "Celebrate devotion, culture and the traditions of the Himalayas.",
    "motif": "mountain",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/kullu-dussehra.svg",
    "layout": 3
  },
  {
    "slug": "pushkar-fair",
    "name": "Pushkar Fair",
    "region": "Rajasthan",
    "greeting": "Pushkar Fair",
    "subline": "Celebrate Rajasthan’s colour, craft, culture and desert spirit.",
    "motif": "desert",
    "bg": "#fff7ed",
    "accent": "#ea580c",
    "fg": "#0f172a",
    "image": "/festivals/pushkar-fair.svg",
    "layout": 0
  },
  {
    "slug": "rann-utsav",
    "name": "Rann Utsav",
    "region": "Gujarat",
    "greeting": "Rann Utsav",
    "subline": "Celebrate craft, music and the magic of the white desert.",
    "motif": "desert",
    "bg": "#f8fafc",
    "accent": "#0ea5e9",
    "fg": "#0f172a",
    "image": "/festivals/rann-utsav.svg",
    "layout": 1
  },
  {
    "slug": "goa-carnival",
    "name": "Goa Carnival",
    "region": "Goa",
    "greeting": "Goa Carnival",
    "subline": "Celebrate music, colour, creativity and coastal joy.",
    "motif": "confetti",
    "bg": "#ecfeff",
    "accent": "#06b6d4",
    "fg": "#0f172a",
    "image": "/festivals/goa-carnival.svg",
    "layout": 2
  },
  {
    "slug": "chithirai-festival",
    "name": "Chithirai Festival",
    "region": "Tamil Nadu",
    "greeting": "Chithirai Festival",
    "subline": "Celebrate heritage, devotion and Madurai’s festive traditions.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/chithirai-festival.svg",
    "layout": 3
  },
  {
    "slug": "puthandu",
    "name": "Puthandu",
    "region": "Tamil Nadu",
    "greeting": "Iniya Puthandu Nalvazhthukkal",
    "subline": "Wishing you a joyful Tamil New Year full of fresh possibilities.",
    "motif": "flower",
    "bg": "#fefce8",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/puthandu.svg",
    "layout": 0
  },
  {
    "slug": "cheti-chand",
    "name": "Cheti Chand",
    "region": "Sindhi",
    "greeting": "Happy Cheti Chand",
    "subline": "Celebrate the Sindhi New Year with hope, harmony and prosperity.",
    "motif": "water",
    "bg": "#ecfeff",
    "accent": "#0284c7",
    "fg": "#0f172a",
    "image": "/festivals/cheti-chand.svg",
    "layout": 1
  },
  {
    "slug": "navroz",
    "name": "Navroz",
    "region": "Parsi",
    "greeting": "Navroz Mubarak",
    "subline": "Wishing you renewal, happiness and a bright new year.",
    "motif": "flower",
    "bg": "#f0fdf4",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/navroz.svg",
    "layout": 2
  },
  {
    "slug": "pateti",
    "name": "Pateti",
    "region": "Parsi",
    "greeting": "Pateti",
    "subline": "A day for reflection, renewal and positive beginnings.",
    "motif": "flower",
    "bg": "#f8fafc",
    "accent": "#64748b",
    "fg": "#0f172a",
    "image": "/festivals/pateti.svg",
    "layout": 3
  },
  {
    "slug": "navreh",
    "name": "Navreh",
    "region": "Kashmir",
    "greeting": "Happy Navreh",
    "subline": "Welcome the Kashmiri New Year with peace, abundance and hope.",
    "motif": "mountain",
    "bg": "#ecfeff",
    "accent": "#0891b2",
    "fg": "#0f172a",
    "image": "/festivals/navreh.svg",
    "layout": 0
  },
  {
    "slug": "ambubachi-mela",
    "name": "Ambubachi Mela",
    "region": "Assam",
    "greeting": "Ambubachi Mela",
    "subline": "Honouring nature, spirituality and a living tradition of Assam.",
    "motif": "temple",
    "bg": "#fff1f2",
    "accent": "#be123c",
    "fg": "#0f172a",
    "image": "/festivals/ambubachi-mela.svg",
    "layout": 1
  },
  {
    "slug": "rath-yatra",
    "name": "Jagannath Rath Yatra",
    "region": "Odisha",
    "greeting": "Jai Jagannath",
    "subline": "Celebrate devotion, community and the grand journey of the chariots.",
    "motif": "chariot",
    "bg": "#fff7ed",
    "accent": "#ea580c",
    "fg": "#0f172a",
    "image": "/festivals/rath-yatra.svg",
    "layout": 2
  },
  {
    "slug": "kharchi-puja",
    "name": "Kharchi Puja",
    "region": "Tripura",
    "greeting": "Kharchi Puja",
    "subline": "Celebrate tradition, devotion and the cultural spirit of Tripura.",
    "motif": "temple",
    "bg": "#f0fdf4",
    "accent": "#15803d",
    "fg": "#0f172a",
    "image": "/festivals/kharchi-puja.svg",
    "layout": 3
  },
  {
    "slug": "garia-puja",
    "name": "Garia Puja",
    "region": "Tripura",
    "greeting": "Garia Puja",
    "subline": "Wishing prosperity, harvest and happiness to every home.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#65a30d",
    "fg": "#0f172a",
    "image": "/festivals/garia-puja.svg",
    "layout": 0
  },
  {
    "slug": "lai-haraoba",
    "name": "Lai Haraoba",
    "region": "Manipur",
    "greeting": "Lai Haraoba",
    "subline": "Celebrate heritage, dance and the sacred traditions of Manipur.",
    "motif": "dance",
    "bg": "#f5f3ff",
    "accent": "#7c3aed",
    "fg": "#0f172a",
    "image": "/festivals/lai-haraoba.svg",
    "layout": 1
  },
  {
    "slug": "moatsu",
    "name": "Moatsu",
    "region": "Nagaland",
    "greeting": "Happy Moatsu",
    "subline": "Celebrate community, harvest and Ao Naga traditions.",
    "motif": "drum",
    "bg": "#fff7ed",
    "accent": "#f59e0b",
    "fg": "#0f172a",
    "image": "/festivals/moatsu.svg",
    "layout": 2
  },
  {
    "slug": "sekrenyi",
    "name": "Sekrenyi",
    "region": "Nagaland",
    "greeting": "Happy Sekrenyi",
    "subline": "Celebrate renewal, culture and the traditions of the Angami community.",
    "motif": "water",
    "bg": "#ecfeff",
    "accent": "#0891b2",
    "fg": "#0f172a",
    "image": "/festivals/sekrenyi.svg",
    "layout": 3
  },
  {
    "slug": "independence-day",
    "name": "Independence Day",
    "region": "National",
    "greeting": "Happy Independence Day",
    "subline": "Celebrate freedom, courage and the spirit of India.",
    "motif": "flag",
    "bg": "#fff7ed",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/independence-day.svg",
    "layout": 0
  },
  {
    "slug": "republic-day",
    "name": "Republic Day",
    "region": "National",
    "greeting": "Happy Republic Day",
    "subline": "Celebrate the Constitution, unity and the strength of our democracy.",
    "motif": "flag",
    "bg": "#eff6ff",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/republic-day.svg",
    "layout": 1
  },
  {
    "slug": "gandhi-jayanti",
    "name": "Gandhi Jayanti",
    "region": "National",
    "greeting": "Gandhi Jayanti",
    "subline": "Remember truth, non-violence and the power of peaceful change.",
    "motif": "spinning",
    "bg": "#f8fafc",
    "accent": "#64748b",
    "fg": "#0f172a",
    "image": "/festivals/gandhi-jayanti.svg",
    "layout": 2
  },
  {
    "slug": "karthigai-deepam",
    "name": "Karthigai Deepam",
    "region": "Tamil Nadu",
    "greeting": "Happy Karthigai Deepam",
    "subline": "May rows of lamps bring light, warmth and prosperity.",
    "motif": "light",
    "bg": "#3f0d12",
    "accent": "#fb923c",
    "fg": "#ffffff",
    "image": "/festivals/karthigai-deepam.svg",
    "layout": 3
  },
  {
    "slug": "thaipusam",
    "name": "Thaipusam",
    "region": "Tamil Nadu",
    "greeting": "Happy Thaipusam",
    "subline": "A day of devotion, courage and spiritual strength.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/thaipusam.svg",
    "layout": 0
  },
  {
    "slug": "aadi-perukku",
    "name": "Aadi Perukku",
    "region": "Tamil Nadu",
    "greeting": "Happy Aadi Perukku",
    "subline": "Celebrate water, nature and the abundance of the monsoon.",
    "motif": "water",
    "bg": "#ecfeff",
    "accent": "#0284c7",
    "fg": "#0f172a",
    "image": "/festivals/aadi-perukku.svg",
    "layout": 1
  },
  {
    "slug": "makaravilakku",
    "name": "Makaravilakku",
    "region": "Kerala",
    "greeting": "Happy Makaravilakku",
    "subline": "Wishing you devotion, light and peace.",
    "motif": "light",
    "bg": "#0f172a",
    "accent": "#f59e0b",
    "fg": "#ffffff",
    "image": "/festivals/makaravilakku.svg",
    "layout": 2
  },
  {
    "slug": "vallam-kali",
    "name": "Vallam Kali",
    "region": "Kerala",
    "greeting": "Vallam Kali",
    "subline": "Celebrate Kerala’s iconic boat races, rhythm and team spirit.",
    "motif": "water",
    "bg": "#ecfeff",
    "accent": "#0891b2",
    "fg": "#0f172a",
    "image": "/festivals/vallam-kali.svg",
    "layout": 3
  },
  {
    "slug": "poila-boishakh",
    "name": "Poila Boishakh",
    "region": "West Bengal",
    "greeting": "Shubho Nobo Borsho",
    "subline": "Welcome the Bengali New Year with joy, prosperity and fresh beginnings.",
    "motif": "flower",
    "bg": "#fff1f2",
    "accent": "#e11d48",
    "fg": "#0f172a",
    "image": "/festivals/poila-boishakh.svg",
    "layout": 0
  },
  {
    "slug": "kali-puja",
    "name": "Kali Puja",
    "region": "West Bengal",
    "greeting": "Shubho Kali Puja",
    "subline": "May strength, protection and light guide your path.",
    "motif": "light",
    "bg": "#111827",
    "accent": "#f43f5e",
    "fg": "#ffffff",
    "image": "/festivals/kali-puja.svg",
    "layout": 1
  },
  {
    "slug": "jamai-shashti",
    "name": "Jamai Shashti",
    "region": "West Bengal",
    "greeting": "Happy Jamai Shashti",
    "subline": "Celebrate family, food and warm Bengali traditions.",
    "motif": "harvest",
    "bg": "#fef3c7",
    "accent": "#b45309",
    "fg": "#0f172a",
    "image": "/festivals/jamai-shashti.svg",
    "layout": 2
  },
  {
    "slug": "shigmo",
    "name": "Shigmo",
    "region": "Goa",
    "greeting": "Happy Shigmo",
    "subline": "Celebrate spring, folk traditions, colour and community.",
    "motif": "dance",
    "bg": "#ecfdf5",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/shigmo.svg",
    "layout": 3
  },
  {
    "slug": "narali-purnima",
    "name": "Narali Purnima",
    "region": "Maharashtra & Konkan",
    "greeting": "Happy Narali Purnima",
    "subline": "Celebrate the sea, gratitude and coastal traditions.",
    "motif": "water",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/narali-purnima.svg",
    "layout": 0
  },
  {
    "slug": "ashadhi-ekadashi",
    "name": "Ashadhi Ekadashi",
    "region": "Maharashtra",
    "greeting": "Ashadhi Ekadashi",
    "subline": "A day of devotion, pilgrimage and spiritual reflection.",
    "motif": "temple",
    "bg": "#f0fdf4",
    "accent": "#15803d",
    "fg": "#0f172a",
    "image": "/festivals/ashadhi-ekadashi.svg",
    "layout": 1
  },
  {
    "slug": "pola",
    "name": "Pola",
    "region": "Maharashtra & Central India",
    "greeting": "Happy Pola",
    "subline": "Celebrate farming, cattle and the spirit of rural India.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#65a30d",
    "fg": "#0f172a",
    "image": "/festivals/pola.svg",
    "layout": 2
  },
  {
    "slug": "gokulashtami-dahi-handi",
    "name": "Dahi Handi",
    "region": "Maharashtra",
    "greeting": "Happy Dahi Handi",
    "subline": "Celebrate teamwork, energy and the joy of Krishna Janmashtami.",
    "motif": "dance",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/gokulashtami-dahi-handi.svg",
    "layout": 3
  },
  {
    "slug": "karaga",
    "name": "Bengaluru Karaga",
    "region": "Karnataka",
    "greeting": "Happy Karaga",
    "subline": "Celebrate Bengaluru’s historic tradition, devotion and community.",
    "motif": "temple",
    "bg": "#f5f3ff",
    "accent": "#7c3aed",
    "fg": "#0f172a",
    "image": "/festivals/karaga.svg",
    "layout": 0
  },
  {
    "slug": "sammakka-saralamma",
    "name": "Sammakka Saralamma Jatara",
    "region": "Telangana",
    "greeting": "Sammakka Saralamma Jatara",
    "subline": "Honouring courage, community and one of India’s largest tribal gatherings.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#dc2626",
    "fg": "#0f172a",
    "image": "/festivals/sammakka-saralamma.svg",
    "layout": 1
  },
  {
    "slug": "mewar-festival",
    "name": "Mewar Festival",
    "region": "Rajasthan",
    "greeting": "Happy Mewar Festival",
    "subline": "Celebrate spring, heritage and the vibrant traditions of Mewar.",
    "motif": "flower",
    "bg": "#fff1f2",
    "accent": "#db2777",
    "fg": "#0f172a",
    "image": "/festivals/mewar-festival.svg",
    "layout": 2
  },
  {
    "slug": "herath",
    "name": "Herath",
    "region": "Kashmir",
    "greeting": "Happy Herath",
    "subline": "Celebrate Kashmiri Shivratri with faith, family and tradition.",
    "motif": "moon",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/herath.svg",
    "layout": 3
  },
  {
    "slug": "minjar-fair",
    "name": "Minjar Fair",
    "region": "Himachal Pradesh",
    "greeting": "Happy Minjar",
    "subline": "Celebrate harvest, rivers and the traditions of Chamba.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/minjar-fair.svg",
    "layout": 0
  },
  {
    "slug": "harela",
    "name": "Harela",
    "region": "Uttarakhand",
    "greeting": "Happy Harela",
    "subline": "Celebrate greenery, monsoon and the blessings of nature.",
    "motif": "leaf",
    "bg": "#ecfdf5",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/harela.svg",
    "layout": 1
  },
  {
    "slug": "sarhul",
    "name": "Sarhul",
    "region": "Jharkhand",
    "greeting": "Happy Sarhul",
    "subline": "Celebrate nature, spring and the cultural traditions of Jharkhand.",
    "motif": "flower",
    "bg": "#f0fdf4",
    "accent": "#15803d",
    "fg": "#0f172a",
    "image": "/festivals/sarhul.svg",
    "layout": 2
  },
  {
    "slug": "bastar-dussehra",
    "name": "Bastar Dussehra",
    "region": "Chhattisgarh",
    "greeting": "Bastar Dussehra",
    "subline": "Celebrate Bastar’s unique traditions, devotion and community.",
    "motif": "temple",
    "bg": "#fff7ed",
    "accent": "#ea580c",
    "fg": "#0f172a",
    "image": "/festivals/bastar-dussehra.svg",
    "layout": 3
  },
  {
    "slug": "sama-chakeva",
    "name": "Sama Chakeva",
    "region": "Bihar",
    "greeting": "Happy Sama Chakeva",
    "subline": "Celebrate sibling bonds, folk art and the season of migration.",
    "motif": "bird",
    "bg": "#fdf2f8",
    "accent": "#db2777",
    "fg": "#0f172a",
    "image": "/festivals/sama-chakeva.svg",
    "layout": 0
  },
  {
    "slug": "dev-deepawali",
    "name": "Dev Deepawali",
    "region": "Uttar Pradesh",
    "greeting": "Happy Dev Deepawali",
    "subline": "May the ghats glow with faith, gratitude and thousands of lights.",
    "motif": "light",
    "bg": "#2a124f",
    "accent": "#f59e0b",
    "fg": "#ffffff",
    "image": "/festivals/dev-deepawali.svg",
    "layout": 1
  },
  {
    "slug": "bhagoria",
    "name": "Bhagoria",
    "region": "Madhya Pradesh",
    "greeting": "Happy Bhagoria",
    "subline": "Celebrate tribal culture, markets, music and springtime joy.",
    "motif": "dance",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/bhagoria.svg",
    "layout": 2
  },
  {
    "slug": "dola-purnima",
    "name": "Dola Purnima",
    "region": "Odisha",
    "greeting": "Happy Dola Purnima",
    "subline": "Celebrate colour, devotion and Odisha’s spring traditions.",
    "motif": "color",
    "bg": "#fff1f2",
    "accent": "#ec4899",
    "fg": "#0f172a",
    "image": "/festivals/dola-purnima.svg",
    "layout": 3
  },
  {
    "slug": "kumar-purnima",
    "name": "Kumar Purnima",
    "region": "Odisha",
    "greeting": "Happy Kumar Purnima",
    "subline": "Celebrate the full moon, youth and Odisha’s festive traditions.",
    "motif": "moon",
    "bg": "#eef2ff",
    "accent": "#6366f1",
    "fg": "#0f172a",
    "image": "/festivals/kumar-purnima.svg",
    "layout": 0
  },
  {
    "slug": "pang-lhabsol",
    "name": "Pang Lhabsol",
    "region": "Sikkim",
    "greeting": "Pang Lhabsol",
    "subline": "Celebrate Sikkim’s sacred mountains, unity and cultural heritage.",
    "motif": "mountain",
    "bg": "#eff6ff",
    "accent": "#2563eb",
    "fg": "#0f172a",
    "image": "/festivals/pang-lhabsol.svg",
    "layout": 1
  },
  {
    "slug": "yaoshang",
    "name": "Yaoshang",
    "region": "Manipur",
    "greeting": "Happy Yaoshang",
    "subline": "Celebrate spring, sports, music and community in Manipur.",
    "motif": "color",
    "bg": "#fdf2f8",
    "accent": "#ec4899",
    "fg": "#0f172a",
    "image": "/festivals/yaoshang.svg",
    "layout": 2
  },
  {
    "slug": "ker-puja",
    "name": "Ker Puja",
    "region": "Tripura",
    "greeting": "Ker Puja",
    "subline": "Celebrate protection, community and the traditions of Tripura.",
    "motif": "temple",
    "bg": "#f0fdf4",
    "accent": "#15803d",
    "fg": "#0f172a",
    "image": "/festivals/ker-puja.svg",
    "layout": 3
  },
  {
    "slug": "nongkrem-dance",
    "name": "Nongkrem Dance Festival",
    "region": "Meghalaya",
    "greeting": "Nongkrem Festival",
    "subline": "Celebrate Khasi culture, dance, gratitude and community.",
    "motif": "dance",
    "bg": "#ecfeff",
    "accent": "#0891b2",
    "fg": "#0f172a",
    "image": "/festivals/nongkrem-dance.svg",
    "layout": 0
  },
  {
    "slug": "tokhu-emong",
    "name": "Tokhu Emong",
    "region": "Nagaland",
    "greeting": "Happy Tokhu Emong",
    "subline": "Celebrate harvest, friendship and Lotha Naga traditions.",
    "motif": "harvest",
    "bg": "#fef3c7",
    "accent": "#b45309",
    "fg": "#0f172a",
    "image": "/festivals/tokhu-emong.svg",
    "layout": 1
  },
  {
    "slug": "solung",
    "name": "Solung",
    "region": "Arunachal Pradesh",
    "greeting": "Happy Solung",
    "subline": "Celebrate agriculture, prosperity and Adi traditions.",
    "motif": "harvest",
    "bg": "#f0fdf4",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/solung.svg",
    "layout": 2
  },
  {
    "slug": "dree",
    "name": "Dree Festival",
    "region": "Arunachal Pradesh",
    "greeting": "Happy Dree",
    "subline": "Celebrate harvest, community and Apatani traditions.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#65a30d",
    "fg": "#0f172a",
    "image": "/festivals/dree.svg",
    "layout": 3
  },
  {
    "slug": "si-donyi",
    "name": "Si-Donyi",
    "region": "Arunachal Pradesh",
    "greeting": "Happy Si-Donyi",
    "subline": "Celebrate nature, harmony and Tagin cultural traditions.",
    "motif": "sun",
    "bg": "#fff7ed",
    "accent": "#f97316",
    "fg": "#0f172a",
    "image": "/festivals/si-donyi.svg",
    "layout": 0
  },
  {
    "slug": "mim-kut",
    "name": "Mim Kut",
    "region": "Mizoram",
    "greeting": "Happy Mim Kut",
    "subline": "Celebrate harvest, remembrance and Mizo traditions.",
    "motif": "harvest",
    "bg": "#fef3c7",
    "accent": "#b45309",
    "fg": "#0f172a",
    "image": "/festivals/mim-kut.svg",
    "layout": 1
  },
  {
    "slug": "wangala-hundred-drums",
    "name": "100 Drums Wangala",
    "region": "Meghalaya",
    "greeting": "Happy Wangala",
    "subline": "Celebrate Garo harvest traditions with rhythm and gratitude.",
    "motif": "drum",
    "bg": "#fff7ed",
    "accent": "#f59e0b",
    "fg": "#0f172a",
    "image": "/festivals/wangala-hundred-drums.svg",
    "layout": 2
  },
  {
    "slug": "bohag-bihu",
    "name": "Bohag Bihu / Rongali Bihu",
    "region": "Assam",
    "greeting": "Happy Rongali Bihu",
    "subline": "Welcome the Assamese New Year with music, dance and springtime joy.",
    "motif": "dance",
    "bg": "#ecfdf5",
    "accent": "#16a34a",
    "fg": "#0f172a",
    "image": "/festivals/bohag-bihu.svg",
    "layout": 3
  },
  {
    "slug": "kati-bihu",
    "name": "Kati Bihu / Kongali Bihu",
    "region": "Assam",
    "greeting": "Happy Kati Bihu",
    "subline": "A season of prayer, hope and care for the growing fields.",
    "motif": "light",
    "bg": "#fefce8",
    "accent": "#ca8a04",
    "fg": "#0f172a",
    "image": "/festivals/kati-bihu.svg",
    "layout": 0
  },
  {
    "slug": "magh-bihu",
    "name": "Magh Bihu / Bhogali Bihu",
    "region": "Assam",
    "greeting": "Happy Bhogali Bihu",
    "subline": "Celebrate harvest, feasts, bonfires and togetherness.",
    "motif": "fire",
    "bg": "#451a03",
    "accent": "#fb923c",
    "fg": "#ffffff",
    "image": "/festivals/magh-bihu.svg",
    "layout": 1
  },
  {
    "slug": "tusu-parab",
    "name": "Tusu Parab",
    "region": "Jharkhand & Eastern India",
    "greeting": "Happy Tusu Parab",
    "subline": "Celebrate harvest, folk songs and rural traditions.",
    "motif": "harvest",
    "bg": "#fefce8",
    "accent": "#65a30d",
    "fg": "#0f172a",
    "image": "/festivals/tusu-parab.svg",
    "layout": 2
  },
  {
    "slug": "karma-festival",
    "name": "Karma Festival",
    "region": "Jharkhand, Odisha & Central India",
    "greeting": "Happy Karma Festival",
    "subline": "Celebrate nature, community, dance and the sacred Karam tree.",
    "motif": "leaf",
    "bg": "#ecfdf5",
    "accent": "#15803d",
    "fg": "#0f172a",
    "image": "/festivals/karma-festival.svg",
    "layout": 3
  }
] as FestivalTemplate[];

export const FESTIVAL_GROUPS = [
  "All",
  ...Array.from(new Set(FESTIVALS.map((item) => item.region))),
];
